import test from 'node:test';
import assert from 'node:assert/strict';
import { compileGrowthContract } from '../growth-contract.ts';
import { calculateGos } from '../gos.ts';
import { calculateImpactLedger } from '../impact-ledger.ts';
import { evaluateMarginShield } from '../margin-shield.ts';
import { simulateScenarios } from '../simulator.ts';
import { transition } from '../state-machines.ts';
import { tamyrGiftSimulation, tamyrGosInputs, tamyrImpactInput } from '../tamyr-fixture.ts';

function compileInput() { const simulator = simulateScenarios(tamyrGiftSimulation); const marginDecision = evaluateMarginShield({ simulator, mechanic: tamyrGiftSimulation.mechanic, averageOrderValueMinor: 3500, contributionMargin: 0.6, minimumContributionPerOrderMinor: 1000, marginFloor: 0.42, budgetMinor: 120000, maxCannibalization: 0.2, cannibalization: 0.1, consentEligibleCount: 18 }); return { schemaVersion: 1, signal: { deltaBps: -2700 }, recommendation: { mechanic: 'gift_with_threshold' }, goal: 'reactivate', audience: { inclusion: ['inactive_30'], exclusion: ['no_consent'], eligibleCount: 18, ruleVersion: 1 }, consentSummary: { scope: 'marketing.whatsapp', granted: 18, excluded: 46, checkedAt: '2026-07-30T00:00:00Z' }, simulator, marginDecision, gos: calculateGos(tamyrGosInputs, { expectedIncrementalContributionMinor: simulator.scenarios.base.incrementalContributionMinor, hasConsent: true, withinLimits: true }), contentBrief: { ru: 'Круассан в подарок', kk: 'Круассан сыйлыққа' }, channel: 'whatsapp', attributionPlan: { trackingCode: 'TAMYR3500' }, stopRule: { maxCostMinor: 7000 }, ownerLimits: { budgetMinor: 120000, marginFloor: 0.42, approvalThresholdMinor: 25000 } }; }
test('compiler requires complete guards and produces immutable versioned snapshot', () => { const contract = compileGrowthContract(compileInput()); assert.equal(contract.status, 'compiled'); assert.equal(contract.version, 1); assert.ok(Object.isFrozen(contract.snapshot)); });
test('approved input change creates new version and requires reapproval', () => { const first = compileGrowthContract(compileInput()); const approved = { ...first, status: 'approved' as const, approvedAt: '2026-07-30T00:00:00Z' }; const changed = compileGrowthContract({ ...compileInput(), channel: 'telegram' }, approved); assert.equal(changed.version, 2); assert.equal(changed.status, 'compiled'); assert.equal(changed.approvedAt, undefined); });
test('compiler blocks missing consent, attribution and blocked Margin Shield', () => { const base = compileInput(); assert.throws(() => compileGrowthContract({ ...base, consentSummary: { ...base.consentSummary, granted: 0 } }), /consent/i); assert.throws(() => compileGrowthContract({ ...base, attributionPlan: {} }), /attribution/i); assert.throws(() => compileGrowthContract({ ...base, marginDecision: { ...base.marginDecision, status: 'blocked' } }), /blocked/i); });
test('state machines reject invalid transitions and optimistic conflicts', () => { assert.throws(() => transition('growth_contract', { state: 'draft', optimisticVersion: 1 }, 'running', 1, 'x'), /not allowed/); assert.throws(() => transition('automation', { state: 'draft', optimisticVersion: 2 }, 'active', 1, 'x'), /version changed/); });
test('repeated idempotency key returns same transition result', () => { const once = transition('growth_contract', { state: 'approved', optimisticVersion: 3 }, 'launching', 3, 'launch-1'); assert.deepEqual(transition('growth_contract', once, 'launching', 4, 'launch-1'), once); });
test('TAMYR Impact Ledger matches canonical mock outcome', () => { const ledger = calculateImpactLedger(tamyrImpactInput); assert.equal(ledger.influencedRevenueMinor, 103500); assert.equal(ledger.incrementalRevenueMinor, 48700); assert.equal(ledger.incrementalContributionMinor, 18200); assert.equal(tamyrImpactInput.fixedCampaignCostMinor, 6800); assert.equal(Math.round((ledger.campaignRoiBps ?? 0) / 100), 168); assert.equal(ledger.timeSavedMinutes, 145); assert.equal(ledger.kind, 'mock_actual'); });
test('ledger refuses mock source as verified fact and separates influenced kind', () => { assert.throws(() => calculateImpactLedger({ ...tamyrImpactInput, kind: 'verified_fact' }), /mock source/); const ledger = calculateImpactLedger(tamyrImpactInput); assert.equal(ledger.numbers.influencedRevenue.kind, 'influenced'); assert.equal(ledger.numbers.incrementalRevenue.kind, 'mock_actual'); });
test('zero denominators return null instead of false precision', () => { const ledger = calculateImpactLedger({ ...tamyrImpactInput, fixedCampaignCostMinor: 0, verifiedNewCustomers: 0, reactivatedCustomers: 0 }); assert.equal(ledger.campaignRoiBps, null); assert.equal(ledger.cacMinor, null); assert.equal(ledger.costPerReturnMinor, null); });
test('CAC, cost per return, LTV and forecast error use deterministic formulas', () => { const ledger=calculateImpactLedger({ ...tamyrImpactInput, acquisitionSpendMinor:10000,verifiedNewCustomers:4,reactivationCostMinor:6800,reactivatedCustomers:8 }); assert.equal(ledger.cacMinor,2500); assert.equal(ledger.costPerReturnMinor,850); assert.equal(ledger.ltvMinor,20700); assert.equal(ledger.forecastErrorPpm,26694); });
test('every ledger number exposes the shared Explain Every Number contract', () => { const ledger=calculateImpactLedger(tamyrImpactInput); for(const item of Object.values(ledger.numbers)){assert.ok(item.what);assert.ok(item.source);assert.ok(item.formula);assert.ok(item.period.start);assert.ok(item.nextAction);assert.ok(item.kind);} });
