import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateGos } from '../gos.ts';
import { evaluateMarginShield } from '../margin-shield.ts';
import { simulateScenarios } from '../simulator.ts';
import { tamyrDiscountSimulation, tamyrGiftSimulation, tamyrGosInputs } from '../tamyr-fixture.ts';

test('TAMYR GOS rounds to 87', () => { assert.equal(calculateGos(tamyrGosInputs, { expectedIncrementalContributionMinor: 18200, hasConsent: true, withinLimits: true }).score, 87); });
test('GOS green is impossible with negative contribution, missing consent or exceeded limits', () => { for (const guards of [{ expectedIncrementalContributionMinor: -1, hasConsent: true, withinLimits: true }, { expectedIncrementalContributionMinor: 1, hasConsent: false, withinLimits: true }, { expectedIncrementalContributionMinor: 1, hasConsent: true, withinLimits: false }]) assert.equal(calculateGos(tamyrGosInputs, guards).status, 'blocked'); });
test('GOS validates every 0..1 input', () => { assert.throws(() => calculateGos({ ...tamyrGosInputs, P: 1.01 }, { expectedIncrementalContributionMinor: 1, hasConsent: true, withinLimits: true }), /between 0 and 1/); });
test('20% blanket discount is blocked by owner margin floor', () => { const simulator = simulateScenarios(tamyrDiscountSimulation); const decision = evaluateMarginShield({ simulator, mechanic: tamyrDiscountSimulation.mechanic, averageOrderValueMinor: 3450, contributionMargin: 0.6, minimumContributionPerOrderMinor: 1000, marginFloor: 0.42, budgetMinor: 120000, maxCannibalization: 0.2, cannibalization: 0.1, consentEligibleCount: 18 }); assert.equal(decision.status, 'blocked'); assert.ok(decision.reasons.includes('owner_margin_floor')); assert.ok(decision.safeAlternatives.some((x) => x.type === 'gift_with_threshold')); });
test('croissant gift at 3500 passes Margin Shield', () => { const simulator = simulateScenarios(tamyrGiftSimulation); const decision = evaluateMarginShield({ simulator, mechanic: tamyrGiftSimulation.mechanic, averageOrderValueMinor: 3500, contributionMargin: 0.6, minimumContributionPerOrderMinor: 1000, marginFloor: 0.42, budgetMinor: 120000, maxCannibalization: 0.2, cannibalization: 0.1, consentEligibleCount: 18 }); assert.notEqual(decision.status, 'blocked'); assert.ok(decision.contributionPerOrderMinor > 0); });
test('budget, consent, negative margin and cannibalization independently block', () => { const simulator = simulateScenarios(tamyrGiftSimulation); const base = { simulator, mechanic: tamyrGiftSimulation.mechanic, averageOrderValueMinor: 3500, contributionMargin: 0.6, minimumContributionPerOrderMinor: 1000, marginFloor: 0.42, budgetMinor: 120000, maxCannibalization: 0.2, cannibalization: 0.1, consentEligibleCount: 18 }; assert.equal(evaluateMarginShield({ ...base, budgetMinor: 1 }).status, 'blocked'); assert.equal(evaluateMarginShield({ ...base, consentEligibleCount: 0 }).status, 'blocked'); assert.equal(evaluateMarginShield({ ...base, contributionMargin: 0.05 }).status, 'blocked'); assert.equal(evaluateMarginShield({ ...base, cannibalization: 0.9 }).status, 'blocked'); });
test('scenario outputs are monotonic for ordered uplift (invariant sweep)', () => { for (let base = 1; base <= 50; base++) { const result = simulateScenarios({ ...tamyrGiftSimulation, eligibleAudience: base * 10 }); assert.ok(result.scenarios.pessimistic.incrementalOrders <= result.scenarios.base.incrementalOrders); assert.ok(result.scenarios.base.incrementalOrders <= result.scenarios.optimistic.incrementalOrders); } });
test('simulator rejects invalid scenario ordering and avoids fractional minor units', () => { assert.throws(() => simulateScenarios({ ...tamyrGiftSimulation, uplift: { pessimistic: 0.8, base: 0.5, optimistic: 0.7 } }), /pessimistic/); const result = simulateScenarios(tamyrGiftSimulation); for (const scenario of Object.values(result.scenarios)) for (const value of [scenario.revenueMinor, scenario.incrementalRevenueMinor, scenario.incrementalContributionMinor, scenario.campaignCostMinor]) assert.equal(Number.isInteger(value), true); });
test('all seven promotion mechanics produce integer benefit cost and scenarios', () => { const mechanics=[{type:'percentage_discount',discountBps:1000},{type:'fixed_discount',discountMinor:300},{type:'2_plus_1',freeUnitCostMinor:500},{type:'gift_with_threshold',giftCostMinor:300,thresholdMinor:3500},{type:'happy_hours',discountBps:800},{type:'return_coupon',couponMinor:300},{type:'bonus_points',liabilityBps:500}] as const; for(const mechanic of mechanics){const result=simulateScenarios({...tamyrGiftSimulation,mechanic});assert.equal(Number.isInteger(result.scenarios.base.campaignCostMinor),true);} });
test('zero channel and fixed costs are valid boundary inputs',()=>{const result=simulateScenarios({...tamyrGiftSimulation,channelCostPerContactMinor:0,fixedCostMinor:0});assert.ok(result.scenarios.base.campaignCostMinor>=0);assert.equal(result.scenarios.base.roiBps,null);});
