import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeBusinessTwin } from '../business-twin.ts';
import { compareComparableWindows } from '../signals.ts';
import { eligibleAudience, recomputeMemberships } from '../segments.ts';
import { tamyrCustomers, tamyrSegmentRules, tamyrTwinInput } from '../tamyr-fixture.ts';

test('TAMYR Twin is ready and every derived field has provenance', () => { const twin = normalizeBusinessTwin(tamyrTwinInput); assert.equal(twin.readiness, 100); assert.deepEqual(twin.missing, []); assert.equal(twin.derived.totalCapacity.value, 38); for (const field of Object.values(twin.derived)) { assert.ok(field.source); assert.ok(field.calculatedAt); assert.ok(field.confidence > 0); } });
test('Twin rejects timezone, currency mismatch and negative margin inputs', () => { assert.throws(() => normalizeBusinessTwin({ ...tamyrTwinInput, profile: { ...tamyrTwinInput.profile, timezone: 'Mars/Olympus' } }), /timezone/i); assert.throws(() => normalizeBusinessTwin({ ...tamyrTwinInput, items: [{ ...tamyrTwinInput.items[0], currency: 'USD' }] }), /currency/i); });
test('comparable weekday 15-18 window produces exact -27% without causal claim', () => { const current = { start: '2026-07-20T00:00:00Z', end: '2026-07-21T00:00:00Z', timezone: 'Asia/Almaty', weekdays: [1], startHour: 15, endHour: 18 }; const baseline = { ...current, start: '2026-07-06T00:00:00Z', end: '2026-07-07T00:00:00Z' }; const result = compareComparableWindows([{ occurredAt: '2026-07-20T10:30:00Z', value: 73 }, { occurredAt: '2026-07-06T10:30:00Z', value: 100 }], current, baseline, 'synthetic comparable fixture'); assert.equal(result.deltaBps, -2700); assert.equal(result.causalClaim, false); });
test('signal detector rejects incomparable timezone windows', () => { const window = { start: '2026-07-20T00:00:00Z', end: '2026-07-21T00:00:00Z', timezone: 'Asia/Almaty', weekdays: [1], startHour: 15, endHour: 18 }; assert.throws(() => compareComparableWindows([], window, { ...window, timezone: 'UTC' }, 'x'), /must match/); });
test('TAMYR segmentation yields 64 inactive and consent-first 18 eligible', () => { const customers = tamyrCustomers(); const memberships = recomputeMemberships(customers, tamyrSegmentRules, '2026-07-30T00:00:00Z'); assert.equal(memberships.filter((x) => x.segment === 'inactive').length, 64); const audience = eligibleAudience(customers, tamyrSegmentRules, '2026-07-30T00:00:00Z', 'inactive', 0.8); assert.equal(audience.eligibleCustomerIds.length, 18); assert.equal(Object.keys(audience.excluded).length, 46); });
test('segment recomputation is deterministic and idempotent', () => { const customers = tamyrCustomers(); assert.deepEqual(recomputeMemberships(customers, tamyrSegmentRules, '2026-07-30T00:00:00Z'), recomputeMemberships([...customers].reverse(), tamyrSegmentRules, '2026-07-30T00:00:00Z')); });
