import { Campaign, ContentItem, ImpactMetric, Tool } from '@/types';

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-01',
    titleRu: 'Возврат спящих гостей: Круассан в подарок при чеке от 3 500 ₸',
    titleKk: 'Ұйқыдағы қонақтарды қайтару: 3 500 ₸ чекке круассан сыйлыққа',
    type: 'gift_min_check',
    status: 'active',
    targetCount: 18,
    sentCount: 18,
    openedCount: 15,
    redeemedCount: 9,
    influencedRevenue: 103500,
    incrementalRevenue: 48700,
    roi: 168,
    startDate: '2026-07-22',
    endDate: '2026-07-29',
  },
  {
    id: 'camp-02',
    titleRu: 'Happy Hours 15:00-18:00: Вторая чашка кофе за 50%',
    titleKk: 'Happy Hours 15:00-18:00: Екінші шыны кофе 50% жеңілдікпен',
    type: 'happy_hours',
    status: 'completed',
    targetCount: 42,
    sentCount: 42,
    openedCount: 38,
    redeemedCount: 24,
    influencedRevenue: 184000,
    incrementalRevenue: 72000,
    roi: 210,
    startDate: '2026-07-10',
    endDate: '2026-07-17',
  },
];

export const mockContentStudioItems: ContentItem[] = [
  {
    id: 'cnt-1',
    channel: 'whatsapp',
    textRu: 'Айгерим, скучаем по вашим визитам! ☕ Приходите в будни с 15:00 до 18:00 — дарим свежайший миндальный круассан при заказе от 3 500 ₸. Поручите обеденную паузу нам! Показать этот код на кассе: QADAM-CROISSANT',
    textKk: 'Айгерім, сізді сағындық! ☕ Жұмыс күндері 15:00-ден 18:00-ге дейін келіңіз — 3 500 ₸-ден басталатын тапсырысқа жаңа бадам круассанын сыйлаймыз. Кассада мына кодты көрсетіңіз: QADAM-CROISSANT',
    ctaTextRu: 'Активировать купон в WhatsApp',
    ctaTextKk: 'Купонды WhatsApp-та белсендіру',
    promoCode: 'QADAM-CROISSANT',
  },
  {
    id: 'cnt-2',
    channel: 'instagram_post',
    textRu: 'Тихие часы — лучшее время для уютного кофе и работы. С 15:00 до 18:00 заказывайте любимые напитки от 3 500 ₸ и получайте подарок от шеф-кондитера! ✨',
    textKk: 'Тыныш сағаттар — жайлы кофе мен жұмыс үшін ең жақсы уақыт. 15:00-ден 18:00-ге дейін 3 500 ₸-ден бастап тапсырыс беріңіз де, бас аспаздан сыйлық алыңыз! ✨',
    ctaTextRu: 'Сохранить промокод',
    ctaTextKk: 'Промокодты сақтау',
  },
  {
    id: 'cnt-3',
    channel: 'telegram',
    textRu: 'Специально для подписчиков нашего канала: заходите на послеобеденный кофе в будни! Подарки к чеку от 3 500 ₸ ждут вас с 15:00 до 18:00.',
    textKk: 'Арна жазылушылары үшін арнайы: жұмыс күндері түскі кофеге келіңіз! 3 500 ₸-ден басталатын чекке сыйлықтар 15:00-ден 18:00-ге дейін күтеді.',
    ctaTextRu: 'Перейти в бот',
    ctaTextKk: 'Ботқа өту',
  },
];

export const mockImpactMetrics: ImpactMetric[] = [
  { id: 'm1', labelRu: 'Целевых получателей', labelKk: 'Мақсатты алушылар', value: 18, type: 'demo_result', unit: 'чел' },
  { id: 'm2', labelRu: 'Прочитали предложение', labelKk: 'Ұсынысты оқыды', value: 15, type: 'demo_result', unit: 'чел' },
  { id: 'm3', labelRu: 'Совершили покупку (Return)', labelKk: 'Сатып алу жасады', value: 9, type: 'demo_result', unit: 'чел' },
  { id: 'm4', labelRu: 'Influenced Revenue', labelKk: 'Ықпал етілген түсім', value: 103500, type: 'demo_result', unit: '₸' },
  { id: 'm5', labelRu: 'Simulated Incremental Revenue', labelKk: 'Симуляцияланған қосымша түсім', value: 48700, type: 'forecast', unit: '₸' },
  { id: 'm6', labelRu: 'Incremental Contribution Profit', labelKk: 'Қосымша маржиналды пайда', value: 18200, type: 'verified_fact', unit: '₸' },
  { id: 'm7', labelRu: 'Simulated ROI', labelKk: 'Симуляцияланған ROI', value: '168%', type: 'forecast' },
  { id: 'm8', labelRu: 'Сэкономлено времени', labelKk: 'Үнемделген уақыт', value: '145 мин', type: 'verified_fact' },
];

export const mockTools: Tool[] = [
  {
    id: 't-1',
    nameRu: 'Margin Shield (Защитник Маржи)',
    nameKk: 'Маржа қорғаушысы',
    category: 'Финансы & Экономика',
    descriptionRu: 'Симулятор маржинальности, блокирующий убыточные скидки и рассчитывающий точную экономику акции.',
    descriptionKk: 'Шығынды жеңілдіктерді бұғаттайтын және акцияның нақты экономикасын есептейтін маржиналдылық симуляторы.',
    iconName: 'ShieldCheck',
    route: '/features/margin-shield',
    isBackendReady: false,
  },
  {
    id: 't-2',
    nameRu: 'QR Loyalty & Consent Engine',
    nameKk: 'QR Лоялдылық жүйесі',
    category: 'Клиенты & Сбор данных',
    descriptionRu: 'Генератор легкого QR на кассе для оцифровки гостей без установки тяжелых приложений.',
    descriptionKk: 'Тіркелусіз және ауыр қосымшаларсыз қонақтарды санға айналдыруға арналған QR генераторы.',
    iconName: 'QrCode',
    route: '/features/qr-loyalty',
    isBackendReady: false,
  },
  {
    id: 't-3',
    nameRu: 'Growth Contract Compiler',
    nameKk: 'Growth келісімшарт компиляторы',
    category: 'AI & Автоматизация',
    descriptionRu: 'Автоматическая сборка сигналов бизнеса в прозрачный исполнимый контракт с условиями остановки.',
    descriptionKk: 'Бизнес сигналдарын тоқтату шарттары бар мөлдір келісімшартқа автоматты түрде жинау.',
    iconName: 'FileCheck',
    route: '/features/growth-contract',
    isBackendReady: false,
  },
  {
    id: 't-4',
    nameRu: 'Multilingual Content Studio',
    nameKk: 'Көптілді контент студиясы',
    category: 'Маркетинг & Контент',
    descriptionRu: 'Адаптация оффера под Instagram, WhatsApp, Telegram и Сценарии видео на русском и казахском языках.',
    descriptionKk: 'Ұсынысты Instagram, WhatsApp, Telegram және видео сценарийлеріне орыс және қазақ тілдерінде бейімдеу.',
    iconName: 'Sparkles',
    route: '/features/content-studio',
    isBackendReady: false,
  },
];
