import { Campaign, ContentItem, ImpactMetric, Tool } from '@/types';

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-01',
    titleRu: 'Возврат спящих гостей: Круассан в подарок при чеке от 3 500 ₸',
    titleKk: 'Ұйқыдағы қонақтарды қайтару: 3 500 ₸ чекке круассан сыйлыққа',
    type: 'gift_min_check',
    status: 'active',
    targetCount: 18,
    sentCount: 18,
    openedCount: 15,
    redeemedCount: 9,
    influencedRevenue: 103500,
    incrementalRevenue: 48700,
    roi: 168,
    startDate: '2026-07-22',
    endDate: '2026-07-29',
  },
  {
    id: 'camp-02',
    titleRu: 'Happy Hours 15:00-18:00: Вторая чашка кофе за 50%',
    titleKk: 'Happy Hours 15:00-18:00: Екінші шыны кофе 50% жеңілдікпен',
    type: 'happy_hours',
    status: 'completed',
    targetCount: 42,
    sentCount: 42,
    openedCount: 38,
    redeemedCount: 24,
    influencedRevenue: 184000,
    incrementalRevenue: 72000,
    roi: 210,
    startDate: '2026-07-10',
    endDate: '2026-07-17',
  },
];

export const mockContentStudioItems: ContentItem[] = [
  {
    id: 'cnt-1',
    channel: 'whatsapp',
    textRu: 'Айгерим, скучаем по вашим визитам! ☕ Приходите в будни с 15:00 до 18:00 — дарим свежайший миндальный круассан при заказе от 3 500 ₸. Поручите обеденную паузу нам! Показать этот код на кассе: QADAM-CROISSANT',
    textKk: 'Айгерім, сізді сағындық! ☕ Жұмыс күндері 15:00-ден 18:00-ге дейін келіңіз — 3 500 ₸-ден басталатын тапсырысқа жаңа бадам круассанын сыйлаймыз. Кассада мына кодты көрсетіңіз: QADAM-CROISSANT',
    ctaTextRu: 'Активировать купон в WhatsApp',
    ctaTextKk: 'Купонды WhatsApp-та белсендіру',
    promoCode: 'QADAM-CROISSANT',
  },
  {
    id: 'cnt-2',
    channel: 'instagram_post',
    textRu: 'Тихие часы — лучшее время для уютного кофе и работы. С 15:00 до 18:00 заказывайте любимые напитки от 3 500 ₸ и получайте подарок от шеф-кондитера! ✨',
    textKk: 'Тыныш сағаттар — жайлы кофе мен жұмыс үшін ең жақсы уақыт. 15:00-ден 18:00-ге дейін 3 500 ₸-ден бастап тапсырыс беріңіз де, бас аспаздан сыйлық алыңыз! ✨',
    ctaTextRu: 'Сохранить промокод',
    ctaTextKk: 'Промокодты сақтау',
  },
  {
    id: 'cnt-3',
    channel: 'telegram',
    textRu: 'Специально для подписчиков нашего канала: заходите на послеобеденный кофе в будни! Подарки к чеку от 3 500 ₸ ждут вас с 15:00 до 18:00.',
    textKk: 'Арна жазылушылары үшін арнайы: жұмыс күндері түскі кофеге келіңіз! 3 500 ₸-ден басталатын чекке сыйлықтар 15:00-ден 18:00-ге дейін күтеді.',
    ctaTextRu: 'Перейти в бот',
    ctaTextKk: 'Ботқа өту',
  },
];

export const mockImpactMetrics: ImpactMetric[] = [
  { id: 'm1', labelRu: 'Позиций на исходе сейчас', labelKk: 'Қазір бітуге жақын позиция', value: 7, type: 'demo_result', unit: 'шт' },
  { id: 'm2', labelRu: 'Решений подтверждено за неделю', labelKk: 'Апта ішінде расталған шешім', value: 12, type: 'demo_result', unit: 'шт' },
  { id: 'm3', labelRu: 'Среднее время доставки', labelKk: 'Орташа жеткізу уақыты', value: '31 ч', type: 'demo_result' },
  { id: 'm4', labelRu: 'Доля сорванных поставок', labelKk: 'Бұзылған жеткізілім үлесі', value: '12%', type: 'demo_result' },
  { id: 'm5', labelRu: 'Прогноз экономии от автозаказа', labelKk: 'Автотапсырыстан үнемдеу болжамы', value: 128400, type: 'forecast', unit: '₸' },
  { id: 'm6', labelRu: 'Заморожено в излишках', labelKk: 'Артық қорда қатып тұр', value: 74900, type: 'forecast', unit: '₸' },
  { id: 'm7', labelRu: 'Сэкономлено времени владельца', labelKk: 'Иесінің үнемделген уақыты', value: '210 мин', type: 'demo_result' },
  { id: 'm8', labelRu: 'Подтверждённый эффект', labelKk: 'Расталған әсер', value: 0, type: 'verified_fact', unit: '₸' },
];

export const mockTools: Tool[] = [
  {
    id: 't-1',
    nameRu: 'Учёт остатков и минимальный запас',
    nameKk: 'Қалдық есебі және ең аз қор',
    category: 'Склад',
    descriptionRu: 'Приёмка, расход, списание и перемещение складываются в один остаток по каждой позиции и точке.',
    descriptionKk: 'Қабылдау, шығыс, есептен шығару және ауыстыру әр позиция бойынша бір қалдыққа жиналады.',
    iconName: 'Boxes',
    route: '/features/stockout-clock',
    isBackendReady: false,
  },
  {
    id: 't-2',
    nameRu: 'Автозаказ поставщику',
    nameKk: 'Жеткізушіге автотапсырыс',
    category: 'Закупки',
    descriptionRu: 'При достижении точки перезаказа собирается черновик заказа: количество, упаковка, минимальная партия.',
    descriptionKk: 'Қайта тапсырыс нүктесіне жеткенде тапсырыс жобасы жиналады.',
    iconName: 'FileCheck',
    route: '/features/decision-contract',
    isBackendReady: false,
  },
  {
    id: 't-3',
    nameRu: 'Сравнение поставщиков',
    nameKk: 'Жеткізушілерді салыстыру',
    category: 'Поставщики',
    descriptionRu: 'Цена, срок, доля поставок вовремя и полностью, минимальная партия и условия — в одной оценке.',
    descriptionKk: 'Баға, мерзім, уақытында жеткізу үлесі және шарттар — бір бағада.',
    iconName: 'Scale',
    route: '/features/supplier-compare',
    isBackendReady: false,
  },
  {
    id: 't-4',
    nameRu: 'Прогноз спроса',
    nameKk: 'Сұраныс болжамы',
    category: 'Аналитика',
    descriptionRu: 'История продаж, день недели и события Казахстана: Наурыз, жара, начало учебного года.',
    descriptionKk: 'Сатылым тарихы, апта күні және Қазақстан оқиғалары.',
    iconName: 'TrendingUp',
    route: '/features/local-pulse',
    isBackendReady: false,
  },
  {
    id: 't-5',
    nameRu: 'Отслеживание доставок',
    nameKk: 'Жеткізілімдерді бақылау',
    category: 'Уведомления',
    descriptionRu: 'Статус каждой поставки, фиксация опозданий и недовоза, пересчёт рейтинга поставщика.',
    descriptionKk: 'Әр жеткізілім мәртебесі, кешігу мен жетпеуді тіркеу, рейтингті қайта санау.',
    iconName: 'Truck',
    route: '/features/community-trust',
    isBackendReady: false,
  },
];
