import { Customer, Segment } from '@/types';

export const mockSegments: Segment[] = [
  {
    id: 'seg-1',
    nameRu: 'Спящие постоянники',
    nameKk: 'Ұйқыдағы тұрақтылар',
    count: 64,
    descriptionRu: 'Клиенты с 3+ визитами, не посещавшие заведение более 30 дней',
    descriptionKk: '3+ рет келген, бірақ 30 күннен астам келмеген клиенттер',
    riskLevel: 'high',
    avgLifetimeValue: 48500,
  },
  {
    id: 'seg-2',
    nameRu: 'Любители кофейных сетов',
    nameKk: 'Кофе жиынтықтарын ұнатушылар',
    count: 42,
    descriptionRu: 'Клиенты, покупающие десерт и напиток вместе',
    descriptionKk: 'Десерт пен сусынды бірге сатып алатын клиенттер',
    riskLevel: 'low',
    avgLifetimeValue: 62000,
  },
  {
    id: 'seg-3',
    nameRu: 'Новички (1 визит)',
    nameKk: 'Жаңадан келгендер (1 сапар)',
    count: 89,
    descriptionRu: 'Присоединились по QR за последние 14 дней, не совершили повторную покупку',
    descriptionKk: 'Соңғы 14 күнде QR арқылы қосылған, қайта сатып алу жасамағандар',
    riskLevel: 'medium',
    avgLifetimeValue: 3200,
  },
  {
    id: 'seg-4',
    nameRu: 'VIP Дневные гости',
    nameKk: 'VIP Күндізгі қонақтар',
    count: 28,
    descriptionRu: 'Высокий чек > 5 000 ₸, заходят регулярно с 12:00 до 16:00',
    descriptionKk: 'Жоғары чек > 5 000 ₸, 12:00-ден 16:00-ге дейін жүйелі келеді',
    riskLevel: 'low',
    avgLifetimeValue: 124000,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c-101',
    name: 'Айгерим Сейтова',
    phone: '+7 701 *** 4589',
    visitCount: 12,
    totalSpent: 42500,
    lastVisitDaysAgo: 34,
    segmentId: 'seg-1',
    preferredChannel: 'whatsapp',
    favoriteCategory: 'Капучино & Круассан',
    avgCheck: 3540,
  },
  {
    id: 'c-102',
    name: 'Данияр Ахметов',
    phone: '+7 707 *** 8812',
    visitCount: 8,
    totalSpent: 28900,
    lastVisitDaysAgo: 42,
    segmentId: 'seg-1',
    preferredChannel: 'whatsapp',
    favoriteCategory: 'Американо & Сэндвич',
    avgCheck: 3610,
  },
  {
    id: 'c-103',
    name: 'Асель Нурланова',
    phone: '+7 777 *** 1102',
    visitCount: 19,
    totalSpent: 78000,
    lastVisitDaysAgo: 4,
    segmentId: 'seg-2',
    preferredChannel: 'telegram',
    favoriteCategory: 'Флэт Уайт & Фисташковый тарт',
    avgCheck: 4105,
  },
  {
    id: 'c-104',
    name: 'Тимур Жаксылыков',
    phone: '+7 702 *** 9934',
    visitCount: 1,
    totalSpent: 3200,
    lastVisitDaysAgo: 11,
    segmentId: 'seg-3',
    preferredChannel: 'whatsapp',
    favoriteCategory: 'Латте Мача',
    avgCheck: 3200,
  },
  {
    id: 'c-105',
    name: 'Мадина Оспанова',
    phone: '+7 705 *** 3341',
    visitCount: 26,
    totalSpent: 135000,
    lastVisitDaysAgo: 2,
    segmentId: 'seg-4',
    preferredChannel: 'whatsapp',
    favoriteCategory: 'Авторский чай & Чизкейк',
    avgCheck: 5190,
  },
];
