import { createHash, randomUUID } from 'node:crypto';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Logo } from '@/components/brand/Logo';
import { DemoBadge } from '@/components/common/DemoBadge';
import { createAdminClient } from '@/lib/supabase/admin';
import { customerPrivacyRequest, joinLoyalty, redeemReward } from './actions';

export const dynamic = 'force-dynamic';
export default async function PublicLoyaltyPage({ params,searchParams }: { params: Promise<{token:string}>; searchParams: Promise<Record<string,string|undefined>> }) {
  const {token}=await params; const query=await searchParams; const admin=createAdminClient();
  const hash='\\x'+createHash('sha256').update(token).digest('hex');
  const {data:qr}=await admin.from('qr_codes').select('id,business_id,loyalty_program_id,status,expires_at,public_context,is_mock').eq('token_hash',hash).eq('purpose','loyalty_join').maybeSingle();
  if(!qr || qr.status!=='active' || (qr.expires_at && new Date(qr.expires_at)<=new Date())) notFound();
  const [{data:business},{data:program},{data:rewards}]=await Promise.all([admin.from('businesses').select('name,status,mode').eq('id',qr.business_id).single(),admin.from('loyalty_programs').select('name,program_type,rules,status').eq('id',qr.loyalty_program_id!).single(),admin.from('rewards').select('id,name_ru,name_kk,cost_points,cost_stamps').eq('loyalty_program_id',qr.loyalty_program_id!).eq('status','active')]);
  if(!business || !program || business.status!=='active' || program.status!=='active') notFound();
  const input='min-h-11 w-full rounded-xl border border-border bg-surface-muted px-4 text-sm outline-none focus:ring-2 focus:ring-primary';
  return <main id="main-content" className="min-h-[100dvh] bg-background px-4 py-8"><div className="mx-auto max-w-lg"><Logo size="md"/><section className="mt-7 rounded-3xl border border-border bg-surface p-6 shadow-xl sm:p-8">{business.mode==='demo' && <DemoBadge label="DEMO DATA · SIMULATED VERIFICATION"/>}<h1 className="mt-4 text-3xl font-extrabold">{business.name}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{program.name}. При присоединении сохраняются masked contact, consent time/source, визиты и loyalty balance. Marketing consent выбирается отдельно.</p>{query.error && <p role="alert" className="mt-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-800">{query.error}</p>}{(query.joined||query.redeemed) && <p role="status" className="mt-4 rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-800">Готово. Balance: {query.stamps} stamps, {query.points} points. {query.duplicate==='1' ? 'Повтор распознан, начисление не дублировано.' : ''}</p>}
  <form action={joinLoyalty} className="mt-6 grid gap-4"><input type="hidden" name="token" value={token}/><input type="hidden" name="idempotencyKey" value={`join:${randomUUID()}`}/><label className="grid gap-2 text-sm font-semibold">Имя<input name="displayName" required className={input}/></label><label className="grid gap-2 text-sm font-semibold">Способ проверки<select name="identityType" className={input}><option value="email">Email</option><option value="phone">Телефон</option></select></label><label className="grid gap-2 text-sm font-semibold">Email или телефон<input name="identity" required autoComplete="email" className={input}/></label><label className="flex gap-3 text-sm leading-5"><input type="checkbox" name="loyaltyConsent" required/>Я согласен участвовать в программе лояльности и хранить историю начислений.</label><label className="flex gap-3 text-sm leading-5"><input type="checkbox" name="marketingConsent"/>Я отдельно согласен получать маркетинговые предложения. Это необязательно.</label><button className="min-h-12 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground">Присоединиться и получить reward</button></form>
  {!!rewards?.length && <details className="mt-6 rounded-2xl border border-border p-4"><summary className="cursor-pointer font-bold">Использовать награду</summary><form action={redeemReward} className="mt-4 grid gap-3"><input type="hidden" name="token" value={token}/><input type="hidden" name="idempotencyKey" value={`redeem:${randomUUID()}`}/><select name="identityType" className={input}><option value="email">Email</option><option value="phone">Телефон</option></select><input name="identity" required placeholder="Тот же email или телефон" className={input}/><select name="rewardId" className={input}>{rewards.map(r=><option key={r.id} value={r.id}>{r.name_ru} ({r.cost_stamps??r.cost_points})</option>)}</select><button className="min-h-11 rounded-xl border border-border font-bold">Redeem</button></form></details>}
  <details className="mt-4 rounded-2xl border border-border p-4"><summary className="cursor-pointer font-bold">Мои данные</summary><form action={customerPrivacyRequest} className="mt-4 grid gap-3"><input type="hidden" name="token" value={token}/><input type="hidden" name="idempotencyKey" value={`privacy:${randomUUID()}`}/><select name="identityType" className={input}><option value="email">Email</option><option value="phone">Телефон</option></select><input name="identity" required placeholder="Email или телефон" className={input}/><select name="requestType" className={input}><option value="export">Запросить export</option><option value="delete">Удалить PII и anonymize</option></select><button className="min-h-11 rounded-xl border border-border font-bold">Отправить запрос</button></form></details><p className="mt-5 text-xs leading-5 text-muted-foreground">В URL нет PII. QR можно отозвать или ротировать. События защищены rate limit и idempotency key.</p></section><p className="mt-5 text-center text-xs text-muted-foreground"><Link href="/privacy" className="underline">Политика конфиденциальности</Link> · <Link href="/terms" className="underline">Условия</Link></p></div></main>;
}
