'use client';
import { useState } from 'react';
import { ChevronLeft, ChevronRight, Signal, Users } from 'lucide-react';
import { QadamSignal } from '@/components/brand/QadamSignal';
export function SectionHeading({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <header className="max-w-3xl">{eyebrow && <p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{eyebrow}</p>}<h2 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-6xl">{title}</h2>{description && <p className="mt-5 text-base leading-7 text-muted-foreground sm:text-lg">{description}</p>}</header>; }
export function BrowserFrame({ children, label = 'QADAM demo' }: { children: React.ReactNode; label?: string }) { return <div className="overflow-hidden rounded-[2rem] border bg-surface shadow-xl"><div className="flex h-12 items-center gap-2 border-b px-5"><i className="size-2 rounded-full bg-danger" /><i className="size-2 rounded-full bg-warning" /><i className="size-2 rounded-full bg-success" /><span className="ml-3 text-xs text-muted-foreground">{label}</span></div>{children}</div>; }
export function PhoneFrame({ children }: { children: React.ReactNode }) { return <div className="mx-auto w-full max-w-[320px] rounded-[2.5rem] border-[6px] border-foreground bg-surface p-3 shadow-xl"><div className="mx-auto mb-3 h-1.5 w-16 rounded-full bg-foreground/30" />{children}</div>; }
export function ProductMockup({ children }: { children: React.ReactNode }) { return <BrowserFrame>{children}</BrowserFrame>; }
export function SignalCard({ title, score }: { title: string; score: number }) { return <article className="rounded-3xl border bg-surface p-5"><Signal className="size-5 text-primary" /><h3 className="mt-4 font-bold">{title}</h3><p className="mt-3 font-mono text-2xl font-bold text-primary">{score}/100</p></article>; }
export function SegmentChip({ children }: { children: React.ReactNode }) { return <span className="inline-flex min-h-11 items-center gap-2 rounded-full border bg-surface px-4 text-sm font-bold"><Users className="size-4 text-primary" />{children}</span>; }
export function GrowthScore({ value }: { value: number }) { return <div className="grid size-24 place-items-center rounded-full border-8 border-primary/20 font-mono text-2xl font-bold text-primary" aria-label={'Growth score ' + value}>{value}</div>; }
export function ScrollStory({ children }: { children: React.ReactNode }) { return <div className="relative space-y-8 lg:min-h-[160vh] lg:space-y-0">{children}</div>; }
export function PageTransition({ children }: { children: React.ReactNode }) { return <div>{children}</div>; }
export function AccessibleCarousel({ items }: { items: { title: string; body: string }[] }) { const [index, setIndex] = useState(0); const move = (delta: number) => setIndex((index + delta + items.length) % items.length); return <section aria-roledescription="carousel" aria-label="Примеры для бизнеса" className="rounded-3xl border bg-surface p-6"><div aria-live="polite"><h3 className="text-xl font-bold">{items[index].title}</h3><p className="mt-2 text-muted-foreground">{items[index].body}</p></div><div className="mt-6 flex gap-2"><button aria-label="Предыдущий слайд" onClick={() => move(-1)} className="grid size-11 place-items-center rounded-full border"><ChevronLeft /></button><button aria-label="Следующий слайд" onClick={() => move(1)} className="grid size-11 place-items-center rounded-full border"><ChevronRight /></button></div></section>; }
export function LanguageToggle() { return <span className="inline-flex rounded-full border bg-surface-muted p-1 text-xs font-bold"><span className="rounded-full bg-surface px-3 py-2">RU</span><span className="px-3 py-2">KK</span></span>; }
export function GrowthContract({ children }: { children: React.ReactNode }) { return <article className="rounded-3xl border bg-surface p-6"><QadamSignal size={32} />{children}</article>; }
export function MarginSimulator({ value = 20 }: { value?: number }) { return <div className="rounded-3xl bg-foreground p-6 text-background"><p className="text-sm opacity-70">Общая скидка</p><p className="mt-2 font-mono text-5xl font-bold">{value}%</p><p className="mt-5 text-sm text-amber-300">Margin Shield: требуется безопасная альтернатива</p></div>; }
export function CTASection({ title, href = '/demo' }: { title: string; href?: string }) { return <section className="rounded-[2.5rem] bg-foreground p-8 text-background sm:p-12"><h2 className="max-w-2xl text-3xl font-bold sm:text-5xl">{title}</h2><a href={href} className="mt-7 inline-flex min-h-11 items-center rounded-full bg-primary px-6 font-bold text-primary-foreground">Открыть демо</a></section>; }
