import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { addCustomerNote, revokeCustomerConsent } from '@/app/app/actions';
import { canManage, getCustomerDetail } from '@/server/qadam/repository';

export const dynamic = 'force-dynamic';

export default async function CustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await getCustomerDetail(id);
  const latestConsent = new Map<string, (typeof data.consents)[number]>();
  data.consents.forEach((item) => { if (!latestConsent.has(item.scope)) latestConsent.set(item.scope, item); });
  return <div className="mx-auto max-w-5xl space-y-6"><Link href="/app/customers" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-primary"><ArrowLeft className="size-4" />К списку</Link><header className="rounded-3xl border border-border bg-surface p-6 sm:p-8"><p className="font-mono text-xs text-muted-foreground">{data.identities[0]?.masked_value ?? 'Identity anonymized'}</p><h1 className="mt-2 text-3xl font-extrabold">{data.customer.display_name || 'Анонимизированный клиент'}</h1><p className="mt-2 text-sm text-muted-foreground">Lifecycle: {data.customer.lifecycle_stage}. Last visit: {data.customer.last_seen_at ? new Date(data.customer.last_seen_at).toLocaleDateString('ru-RU') : 'нет данных'}.</p></header>
    <section className="grid gap-3 sm:grid-cols-4">{[['Визиты',data.metrics.visits],['Всего',data.metrics.totalMinor.toLocaleString('ru-RU')+' ₸'],['AOV',data.metrics.aovMinor.toLocaleString('ru-RU')+' ₸'],['Частота',data.metrics.frequencyPerMonth+'/мес']].map(([label,value]) => <article key={label} className="rounded-2xl border border-border bg-surface p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-xl font-bold">{value}</p></article>)}</section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-border bg-surface p-6"><h2 className="text-xl font-bold">Consent</h2><div className="mt-4 grid gap-3">{[...latestConsent.values()].map((consent) => <div key={consent.scope} className="flex items-center justify-between rounded-xl bg-surface-muted p-3"><div><strong className="text-sm">{consent.scope}</strong><p className="text-xs text-muted-foreground">{consent.status} · {consent.source}</p></div>{canManage(data.role) && consent.status === 'granted' && <form action={revokeCustomerConsent}><input type="hidden" name="customerId" value={id} /><input type="hidden" name="scope" value={consent.scope} /><button className="min-h-11 rounded-xl border border-border px-3 text-xs font-bold">Отозвать</button></form>}</div>)}</div></section><section className="rounded-3xl border border-border bg-surface p-6"><h2 className="text-xl font-bold">Loyalty</h2><div className="mt-4 grid gap-3">{data.accounts.length ? data.accounts.map((account) => <p key={account.id} className="rounded-xl bg-surface-muted p-4 font-mono text-sm">{account.stamps_balance} stamps · {account.points_balance} points</p>) : <p className="text-sm text-muted-foreground">Аккаунта лояльности нет.</p>}</div></section></div>
    <section className="rounded-3xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Заметки и activity</h2><Link href={`/app/campaigns/new?customer=${id}`} className="inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Создать оффер</Link></div>{canManage(data.role) && <form action={addCustomerNote} className="mt-4 flex gap-2"><input type="hidden" name="customerId" value={id} /><label className="sr-only" htmlFor="note">Новая заметка</label><input id="note" name="note" maxLength={5000} required className="min-h-11 flex-1 rounded-xl bg-surface-muted px-4 text-sm" placeholder="Заметка без sensitive targeting" /><button className="rounded-xl border border-border px-4 text-sm font-bold">Сохранить</button></form>}<div className="mt-5 grid gap-3">{data.notes.map((note) => <p key={note.id} className="rounded-xl bg-surface-muted p-3 text-sm">{note.note}<span className="mt-1 block text-xs text-muted-foreground">{new Date(note.created_at).toLocaleString('ru-RU')}</span></p>)}</div></section>
  </div>;
}
